// GENERATED by scripts/gen_env.sh — do not edit. Source: .env.local
abstract final class EnvG {
  static const flavor = 'local';
  static const serverUrl = 'http://localhost:8080';
  static const appVersion = '1.0.0';
}
