#!/bin/bash
# Regenerate lib/app/config/env.g.dart from a .env.<flavor> file.
#
# Env values are baked in at compile time, so any .env change (including
# set_local_ip.sh rewriting SERVER_URL) is invisible until this runs.
# App version is read from pubspec.yaml so it has a single owner.
#
# Usage: scripts/gen_env.sh [local|dev|prod]   (default: local)

set -euo pipefail

FLAVOR="${1:-local}"
PROJECT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$PROJECT_DIR/.env.$FLAVOR"

if [ ! -f "$ENV_FILE" ]; then
  echo "Error: $ENV_FILE not found"
  exit 1
fi

# shellcheck disable=SC1090
source "$ENV_FILE"

if [ -z "${SERVER_URL:-}" ]; then
  echo "Error: SERVER_URL must be set in $ENV_FILE"
  exit 1
fi

APP_VERSION=$(grep '^version:' "$PROJECT_DIR/pubspec.yaml" | tr -d ' ' | sed 's/version://; s/+.*//')

cat > "$PROJECT_DIR/lib/app/config/env.g.dart" <<EOF
// GENERATED by scripts/gen_env.sh — do not edit. Source: .env.$FLAVOR
abstract final class EnvG {
  static const flavor = '$FLAVOR';
  static const serverUrl = '$SERVER_URL';
  static const appVersion = '$APP_VERSION';
}
EOF

echo "env.g.dart generated from .env.$FLAVOR (SERVER_URL=$SERVER_URL, version=$APP_VERSION)"
