#!/bin/bash
# Regenerate the Android cleartext allowlist for this machine's /24 subnet.
#
# Android's network_security_config cannot express a CIDR range, so real-device
# HTTP testing needs every host of the local subnet enumerated. This writes the
# whole file — localhost/emulator entries plus <prefix>.0-255 — from scratch,
# so it is safe to re-run whenever the network changes.

set -euo pipefail

IP=$(ipconfig getifaddr en0)

if [ -z "$IP" ]; then
  echo "Error: Could not get IP address from en0"
  exit 1
fi

PREFIX=$(echo "$IP" | cut -d. -f1-3)
XML_FILE="$(cd "$(dirname "$0")/.." && pwd)/android/app/src/main/res/xml/network_security_config.xml"
mkdir -p "$(dirname "$XML_FILE")"

{
  cat <<'EOF'
<?xml version="1.0" encoding="utf-8"?>
<!-- GENERATED by scripts/set_android_subnet.sh — do not edit by hand. -->
<network-security-config>
    <!-- Local development over plain HTTP -->
    <domain-config cleartextTrafficPermitted="true">
        <domain includeSubdomains="true">localhost</domain>
        <domain includeSubdomains="true">10.0.2.2</domain>
        <domain includeSubdomains="true">127.0.0.1</domain>
EOF
  for i in $(seq 0 255); do
    echo "        <domain includeSubdomains=\"true\">$PREFIX.$i</domain>"
  done
  cat <<'EOF'
    </domain-config>

    <!-- Default: HTTPS only -->
    <base-config cleartextTrafficPermitted="false">
        <trust-anchors>
            <certificates src="system" />
        </trust-anchors>
    </base-config>
</network-security-config>
EOF
} > "$XML_FILE"

echo "network_security_config.xml regenerated for $PREFIX.0/24"
